package MTComparEval::Schema::TestDatabase;

use strict;
use base qw/DBIx::Class::Schema::Loader/;

__PACKAGE__->loader_options(
    relationships => '1',
    use_namespaces => '1',
    components => ["InflateColumn::DateTime"],
);

=head1 NAME

MTComparEval::Schema::TestDatabase - L<DBIx::Class::Schema::Loader> class

=head1 SYNOPSIS

See L<MTComparEval>

=head1 DESCRIPTION

Dynamic L<DBIx::Class::Schema::Loader> schema for use in L<MTComparEval::Model::TestDatabase>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.38

=head1 AUTHOR

A clever guy

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;

